//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIPA_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class estadoperfilranking
    {
        public string idestadoperfil { get; set; }
        public int nivelraking { get; set; }
        public Nullable<int> puntosactuales { get; set; }
        public Nullable<int> posicionglobalranking { get; set; }
    
        public virtual rankingglobal rankingglobal { get; set; }
    }
}
