//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIPA_V2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vipa_databaseEntities : DbContext
    {
        public vipa_databaseEntities()
            : base("name=vipa_databaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<consejo> consejoes { get; set; }
        public virtual DbSet<cuentaverificada> cuentaverificadas { get; set; }
        public virtual DbSet<detallereporteusuariocliente> detallereporteusuarioclientes { get; set; }
        public virtual DbSet<distrito> distritoes { get; set; }
        public virtual DbSet<estadoperfilranking> estadoperfilrankings { get; set; }
        public virtual DbSet<notificacion> notificacions { get; set; }
        public virtual DbSet<preguntafrecuente> preguntafrecuentes { get; set; }
        public virtual DbSet<rankingglobal> rankingglobals { get; set; }
        public virtual DbSet<reportador> reportadors { get; set; }
        public virtual DbSet<reporte> reportes { get; set; }
        public virtual DbSet<terminocondicion> terminocondicions { get; set; }
        public virtual DbSet<tiporeporte> tiporeportes { get; set; }
        public virtual DbSet<usuarioscliente> usuariosclientes { get; set; }
        public virtual DbSet<valoracionreporte> valoracionreportes { get; set; }
    }
}
