//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIPA_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class reporte
    {
        public string idreporte { get; set; }
        public string idreportador { get; set; }
        public int idtiporeporte { get; set; }
        public string idurlvideo { get; set; }
        public string idurlgps { get; set; }
        public string nombredistrito { get; set; }
        public string idplacavehiculo { get; set; }
        public string descripcionreporte { get; set; }
        public string estadoreporte { get; set; }
        public Nullable<System.DateTime> fechacreacion { get; set; }
    
        public virtual tiporeporte tiporeporte { get; set; }
    }
}
