//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VIPA_V2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class valoracionreporte
    {
        public string idvaloracion { get; set; }
        public string segundotipovaloracion { get; set; }
        public string idreporte { get; set; }
        public string idreportador { get; set; }
        public int idtiporeporte { get; set; }
    }
}
